// Auto-generated by packages/contracts/scripts/deploy.js — do not edit by hand.
export const NINK_CHAIN_CONFIG = {
  chainId: 31337,
  tokenAddress: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  registryAddress: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  treasury: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  anchorFeeWei: "10000000000000000",
  deployedAt: "2026-06-16T03:34:50.729Z",
};

export const NINK_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
];

export const NINK_REGISTRY_ABI = [
  "function anchorState(bytes32 stateHash)",
  "function anchorFee() view returns (uint256)",
  "function setAnchorFee(uint256 _newFee)",
  "function ninkToken() view returns (address)",
  "function treasury() view returns (address)",
  "event AnchorRecorded(bytes32 indexed stateHash, address indexed recorder, uint256 feePaid)",
  "event AnchorFeeUpdated(uint256 oldFee, uint256 newFee)",
];

/** @deprecated Legacy dev registry ABI — use NINK_REGISTRY_ABI for production. */
export const NINK_ANCHOR_REGISTRY_ABI = [
  "function anchorProof(bytes32 _stateHash, uint32 _platformId, uint64 _timestamp)",
  "function isAnchored(bytes32 stateHash) view returns (bool)",
  "event LogAnchorCreated(bytes32 indexed stateHash, address indexed validator, uint32 platformId, uint64 timestamp)",
  "error AlreadyAnchored(bytes32 stateHash)",
];
