const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  const treasury = process.env.NINK_TREASURY_ADDRESS || deployer.address;

  console.log("Deployer:", deployer.address);
  console.log("Treasury:", treasury);

  // 1) Fixed-supply NINK token — full mint to deployer
  const Token = await ethers.getContractFactory("ProjectNinkToken");
  const token = await Token.deploy(deployer.address);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();

  console.log("ProjectNinkToken deployed to:", tokenAddress);
  console.log(
    "Total supply:",
    ethers.formatEther(await token.totalSupply()),
    "NINK"
  );

  // 2) Production registry — fee defaults to 0.01 NINK in contract
  const Registry = await ethers.getContractFactory("NinkRegistry");
  const registry = await Registry.deploy(
    deployer.address,
    tokenAddress,
    treasury
  );
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();

  const anchorFee = await registry.anchorFee();
  console.log("NinkRegistry deployed to:", registryAddress);
  console.log("Initial anchorFee:", anchorFee.toString(), "wei");
  console.log("Initial anchorFee:", ethers.formatEther(anchorFee), "NINK");

  const network = await ethers.provider.getNetwork();
  const chainId = Number(network.chainId);

  const deployment = {
    chainId,
    tokenAddress,
    registryAddress,
    treasury,
    deployer: deployer.address,
    anchorFee: anchorFee.toString(),
    anchorFeeNink: ethers.formatEther(anchorFee),
    tokenName: "Project NINK",
    tokenSymbol: "NINK",
    tokenDecimals: 18,
    totalSupply: (await token.totalSupply()).toString(),
    deployedAt: new Date().toISOString(),
    blockNumber: await ethers.provider.getBlockNumber(),
  };

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });
  const deploymentPath = path.join(deploymentsDir, `${chainId}.json`);
  fs.writeFileSync(deploymentPath, JSON.stringify(deployment, null, 2));

  const chainConfigPath = path.join(
    __dirname,
    "..",
    "..",
    "..",
    "browser-plugin",
    "src",
    "config",
    "chainConfig.js"
  );

  const chainConfig = `// Auto-generated by packages/contracts/scripts/deploy.js — do not edit by hand.
export const NINK_CHAIN_CONFIG = {
  chainId: ${chainId},
  tokenAddress: "${tokenAddress}",
  registryAddress: "${registryAddress}",
  treasury: "${treasury}",
  deployer: "${deployer.address}",
  anchorFeeWei: "${anchorFee.toString()}",
  deployedAt: "${deployment.deployedAt}",
};

export const NINK_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
];

export const NINK_REGISTRY_ABI = [
  "function anchorState(bytes32 stateHash)",
  "function anchorFee() view returns (uint256)",
  "function setAnchorFee(uint256 _newFee)",
  "function ninkToken() view returns (address)",
  "function treasury() view returns (address)",
  "event AnchorRecorded(bytes32 indexed stateHash, address indexed recorder, uint256 feePaid)",
  "event AnchorFeeUpdated(uint256 oldFee, uint256 newFee)",
];

/** @deprecated Legacy dev registry ABI — use NINK_REGISTRY_ABI for production. */
export const NINK_ANCHOR_REGISTRY_ABI = [
  "function anchorProof(bytes32 _stateHash, uint32 _platformId, uint64 _timestamp)",
  "function isAnchored(bytes32 stateHash) view returns (bool)",
  "event LogAnchorCreated(bytes32 indexed stateHash, address indexed validator, uint32 platformId, uint64 timestamp)",
  "error AlreadyAnchored(bytes32 stateHash)",
];
`;

  fs.mkdirSync(path.dirname(chainConfigPath), { recursive: true });
  fs.writeFileSync(chainConfigPath, chainConfig);

  console.log("Wrote:", path.join("deployments", `${chainId}.json`));
  console.log("Updated:", chainConfigPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
